### PR TITLE
Updated discord link

### LINKED ISSUE #12: Update Discord Invite Link
Chang to http://discord.eddiehub.org

- [x] .github/ISSUE_TEMPLATE/feature.md
- [x] readme

### PR DESCRIPTION
**Pull request by Arun-kc**
Fixes #12

## Proposed Changes

  - Changing discord link in readme and .github/ISSUE_TEMPLATE/feature.md to http://discord.eddiehub.org

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
LGTM 🚀

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Great collaboration 👍

**Comment by Arun-kc** [comment]
Happy to help @eddiejaoude 👍 and thanks for giving me this opportunity @schmelto 😄

**Pull request merged**
