### PR TITLE
docs: add another example to the readme

### PR DESCRIPTION
**Pull request by schmelto**
## Proposed Changes

Due the readme says that a label should have a emoji at the forst place I think it would be a good to enhance the example at the bottom of the readme with an example with emoji at the beginning

### CODE REVIEW

**Comment by Rahma-AlWadhahi** [comment]
I agree with you @schmelto. Most of the labels have emojis at the beginning, except for these
```json
  {
    "name": "good first issue",
    "color": "7f0799"
  },
  {
    "name": "help wanted",
    "color": "7f0799"
  },
  {
    "name": "duplicate",
    "color": "7f0799"
  },
```
This brings another question, should we add emojis to these so that it would be consistent or should we only add another example in README to show that emojis can be added?

**Comment by schmelto** [comment]
> This brings another question, should we add emojis to these so that it would be consistent or should we only add another example in README to show that emojis can be added?

Good point. Think those labels are common standard and should not have emojis at the beginning (see [here](https://opensource.creativecommons.org/contributing-code/repo-labels/) may we can add a disclaimer in the readme, that the preferred way is with emoji but for common standards as `help wanted` etc. A label without emoji is good to go 🤔

**Comment by Rahma-AlWadhahi** [comment]
> Good point. Think those labels are common standard and should not have emojis at the beginning (see [here](https://opensource.creativecommons.org/contributing-code/repo-labels/) may we can add a disclaimer in the readme, that the preferred way is with emoji but for common standards as `help wanted` etc. A label without emoji is good to go 🤔

hmm, we already have a label standards section in readme. Would a disclaimer help to emphasize the idea of which labeling standards we follow?
Screen Shot 2021-04-24 at 15 43 02

**Comment by schmelto** [comment]
> hmm, we already have a label standards section in readme. Would a disclaimer help to emphasize the idea of which labeling standards we follow?

May we can enhance this section a little bit 🤔

Or provide in the examples both types as this PR will do woth a little side note that some labels don't have to use the emoji as standard 

> I'm sorry, it sounds like I am getting off topic 😓 

No it's fine don't think you're getting off topic

**Comment by schmelto** [comment]
I thought of something like this:

"> This example shows two common ways to add a label one without emoji and the other with emoji. Preferred way is the one with emoji at the beginning but there are also some labels which are commonly used without emojis."

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Comment by eddiejaoude** [comment]
Great collaboration, thank you both 👍

**Pull request merged**
